//! Relative-position bucketing for DeBERTa-v3 disentangled attention.
//!
//! Verbatim port of HF transformers' `make_log_bucket_position` and
//! `build_relative_position` (modeling_deberta_v2.py). The buckets are
//! pre-baked into the rel-embedding table at indices
//! `[0, 2*position_buckets)`; this module produces the per-(query, key)
//! lookup index used by the c2p / p2c gathers.
//!
//! For our v0 inputs (≤480 tokens, position_buckets=256, max_position=512)
//! most (q, k) pairs land in the linear band `|q − k| < 128` and the log
//! branch is unused — but we implement both for correctness on long
//! inputs and to match the oracle bit-for-bit.

/// Bucketed relative position from query `q` to key `k`, signed.
/// Returns a value in `[-(bucket_size - 1), bucket_size - 1]`. Adding
/// `bucket_size` and clamping into `[0, 2*bucket_size − 1]` yields the
/// index used by `rel_embeddings.gather`.
#[inline]
pub fn log_bucket_position(rel_pos: i32, bucket_size: i32, max_position: i32) -> i32 {
    let sign = rel_pos.signum();
    let mid = bucket_size / 2;
    let abs_pos = if rel_pos < mid && rel_pos > -mid {
        mid - 1
    } else {
        rel_pos.abs()
    };
    if abs_pos <= mid {
        // Inside the linear band — keep the signed offset as-is.
        rel_pos
    } else {
        let mid_f = mid as f32;
        let log_pos = ((abs_pos as f32 / mid_f).ln() / ((max_position - 1) as f32 / mid_f).ln()
            * (mid - 1) as f32)
            .ceil() as i32
            + mid;
        sign * log_pos
    }
}

/// Materialise the `[L, L]` table of bucketed `(q − k)` indices ready
/// for gather. Output values are in `[0, 2 * bucket_size)` — already
/// shifted by `bucket_size` and clamped to the embedding table size.
pub fn build_relative_position_matrix(
    seq_len: usize,
    bucket_size: usize,
    max_position: usize,
) -> Vec<i32> {
    let bucket_size_i = bucket_size as i32;
    let max_pos_i = max_position as i32;
    let span = 2 * bucket_size_i;
    let mut out = vec![0i32; seq_len * seq_len];
    for q in 0..seq_len {
        for k in 0..seq_len {
            let raw = q as i32 - k as i32;
            let b = log_bucket_position(raw, bucket_size_i, max_pos_i);
            let shifted = (b + bucket_size_i).clamp(0, span - 1);
            out[q * seq_len + k] = shifted;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Match-the-reference smoke check. For position_buckets=256,
    /// max_position=512 and offsets `[−1, 0, 1, 100, 127, 128, 200,
    /// 511]` the HF reference produces these unsigned bucket indices
    /// (after +256 shift). Generated by running
    /// `make_log_bucket_position(rel, 256, 512) + 256` against HF
    /// transformers and reading the values back.
    #[test]
    fn log_buckets_match_reference() {
        // (rel_pos, expected_signed_bucket)
        let cases: &[(i32, i32)] = &[
            (0, 0),
            (-1, -1),
            (1, 1),
            (-100, -100),
            (100, 100),
            (-127, -127),
            (127, 127),
            (128, 128),  // boundary — stays linear (|128| <= mid)
            (-128, -128),
            (129, 129),  // first log-band value
            (200, 169),  // log-bucketed (verified against HF reference)
            (511, 255),  // max input → max bucket
            (-511, -255),
        ];
        for (rel, expected) in cases {
            let got = log_bucket_position(*rel, 256, 512);
            assert_eq!(got, *expected, "rel_pos={rel}");
        }
    }

    #[test]
    fn matrix_for_short_seq_is_local_linear() {
        // For seq_len << 128 every offset is in the linear band so
        // build_relative_position_matrix collapses to q − k + 256.
        let m = build_relative_position_matrix(4, 256, 512);
        // Expected (with +256 shift):
        // q=0: [256, 255, 254, 253]
        // q=1: [257, 256, 255, 254]
        // q=2: [258, 257, 256, 255]
        // q=3: [259, 258, 257, 256]
        let expected = [
            256, 255, 254, 253,
            257, 256, 255, 254,
            258, 257, 256, 255,
            259, 258, 257, 256,
        ];
        assert_eq!(m, expected);
    }
}
