use crate::embed::EMBEDDING_DIM;

/// One 384-dim prototype vector - the average embedding of the phrases
/// in one pole of one intent dimension.
pub type Prototype = [f32; EMBEDDING_DIM];

/// High and low pole prototypes for one intent dimension.
pub struct PolePair {
    pub high: Prototype,
    pub low: Prototype,
}

/// All four intent dimensions, each with its high/low pole pair.
/// Built once at startup via `load_intent_prototypes`.
pub struct IntentPrototypes {
    pub conviction: PolePair,
    pub prediction_error: PolePair,
    pub arousal: PolePair,
    pub curiosity: PolePair,
}

// Eight prototype vectors baked into the binary at compile time.
// File format: tightly packed `[f32; EMBEDDING_DIM]` little-endian, no header.
// Generated by `examples/gen_prototype_vectors.rs` from `seed_pack.yaml`.
const CONVICTION_HIGH: &[u8] = include_bytes!("prototype_vectors/conviction_high.bin");
const CONVICTION_LOW: &[u8] = include_bytes!("prototype_vectors/conviction_low.bin");
const PREDICTION_ERROR_HIGH: &[u8] = include_bytes!("prototype_vectors/prediction_error_high.bin");
const PREDICTION_ERROR_LOW: &[u8] = include_bytes!("prototype_vectors/prediction_error_low.bin");
const AROUSAL_HIGH: &[u8] = include_bytes!("prototype_vectors/arousal_high.bin");
const AROUSAL_LOW: &[u8] = include_bytes!("prototype_vectors/arousal_low.bin");
const CURIOSITY_HIGH: &[u8] = include_bytes!("prototype_vectors/curiosity_high.bin");
const CURIOSITY_LOW: &[u8] = include_bytes!("prototype_vectors/curiosity_low.bin");

/// Build all eight prototypes from the embedded byte slices. Cheap (8 x 384 f32 reads);
/// call once per startup and cache.
pub fn load_intent_prototypes() -> IntentPrototypes {
    IntentPrototypes {
        conviction: PolePair {
            high: parse(CONVICTION_HIGH),
            low: parse(CONVICTION_LOW),
        },
        prediction_error: PolePair {
            high: parse(PREDICTION_ERROR_HIGH),
            low: parse(PREDICTION_ERROR_LOW),
        },
        arousal: PolePair {
            high: parse(AROUSAL_HIGH),
            low: parse(AROUSAL_LOW),
        },
        curiosity: PolePair {
            high: parse(CURIOSITY_HIGH),
            low: parse(CURIOSITY_LOW),
        },
    }
}

// Parse a tightly-packed `[f32; EMBEDDING_DIM]` little-endian byte slice into a
// fixed-size array. Panics if the byte length doesn't match.
fn parse(bytes: &[u8]) -> Prototype {
    assert_eq!(
        bytes.len(),
        EMBEDDING_DIM * 4,
        "prototype byte slice must be EMBEDDING_DIM * 4 bytes"
    );
    let mut out = [0.0f32; EMBEDDING_DIM];
    for (slot, chunk) in out.iter_mut().zip(bytes.chunks_exact(4)) {
        *slot = f32::from_le_bytes(chunk.try_into().expect("chunk is 4 bytes"));
    }
    out
}
