//! Day-zero Hypergraph loader.
//!
//! `src/seed/graph.bin` is built by `examples/gen_seed_graph.rs` from
//! `seed_pack.yaml` — see that file for the canonical format
//! description. This module decodes the embedded bytes back into a
//! `Hypergraph` and rebuilds the derived indices.
//!
//! The bin file is regenerated by hand:
//!     cargo run --release --example gen_seed_graph
//!
//! Pattern matches `intent_classifiers.rs`: bytes are baked into the
//! binary via `include_bytes!`, deserialized with a hand-rolled
//! little-endian reader, no `serde` dependency in the runtime crate.

use crate::embed::EMBEDDING_DIM;
use crate::types::{
    Attribute, Element, ElementId, Hypergraph, MemoryStats, Relation, RelationId, RelationStatus,
    Term, Tick,
};

/// On-disk format version. Bumped by the generator if the byte layout
/// changes; the runtime refuses to load a mismatched version.
const FORMAT_VERSION: u32 = 1;

const SEED_GRAPH: &[u8] = include_bytes!("seed/graph.bin");

/// Decode the embedded seed graph and return a fully-indexed
/// Hypergraph. Called once at startup; cheap (~150 KB to walk, no
/// model calls). Panics if the bin's format version doesn't match
/// `FORMAT_VERSION` — that's a build-time-vs-runtime mismatch and
/// regenerating the bin is the fix.
pub fn load_seed_graph() -> Hypergraph {
    let mut r = Reader::new(SEED_GRAPH);

    let version = r.u32();
    assert_eq!(
        version, FORMAT_VERSION,
        "seed graph format version mismatch — regenerate src/seed/graph.bin via `cargo run --release --example gen_seed_graph`",
    );

    let element_count = r.u32() as usize;
    let relation_count = r.u32() as usize;
    let void = ElementId(r.u32());
    let genesis = ElementId(r.u32());
    let region_class = ElementId(r.u32());
    let reference_frame_class = ElementId(r.u32());
    let subject_attr = ElementId(r.u32());
    let parent_region_attr = ElementId(r.u32());
    let prototype_attr = ElementId(r.u32());

    let mut elements = Vec::with_capacity(element_count);
    for _ in 0..element_count {
        elements.push(read_element(&mut r));
    }

    let mut relations = Vec::with_capacity(relation_count);
    for _ in 0..relation_count {
        relations.push(read_relation(&mut r));
    }

    assert!(
        r.is_done(),
        "seed graph decoder finished with {} bytes remaining — format drift?",
        r.remaining(),
    );

    let mut hg = Hypergraph {
        elements,
        relations,
        void,
        genesis,
        region_class,
        reference_frame_class,
        subject_attr,
        parent_region_attr,
        prototype_attr,
        ..Hypergraph::default()
    };
    rebuild_indices(&mut hg);
    hg
}

/// Rebuild `Hypergraph`'s derived indices from `elements` + `relations`.
/// Called by [`load_seed_graph`] after deserialization, and by tests
/// that hand-build a hypergraph. The relation graph is authoritative;
/// the indices are a denormalized read cache, so rebuilding them is
/// always safe and idempotent.
///
/// One pass over `relations`:
/// - attributes naming `parent_region_attr` with a `Term::Element(parent)`
///   value push `subject` onto `region_children[parent]` and
///   `(parent, stats.confidence)` onto `region_parents[subject]`.
/// - attributes naming `prototype_attr` with a `Term::Element(proto)`
///   value push `proto` onto `region_prototypes[subject]`.
///
/// One pass over `elements` to (re)populate `by_name` from each
/// element's `names`.
///
/// Clears each index before refilling, so callers don't have to worry
/// about residual state from a prior build.
pub fn rebuild_indices(hg: &mut Hypergraph) {
    hg.by_name.clear();
    hg.region_children.clear();
    hg.region_parents.clear();
    hg.region_prototypes.clear();

    for e in &hg.elements {
        for name in &e.names {
            hg.by_name.entry(name.clone()).or_default().push(e.id);
        }
    }

    for r in &hg.relations {
        // Find the subject. A relation without a subject attribute has
        // no role to play in the region indices — could be a future
        // meta-relation or a malformed entry; either way, skip it.
        let subject = match find_subject(r, hg.subject_attr) {
            Some(s) => s,
            None => continue,
        };
        for attr in &r.attributes {
            if attr.name == hg.subject_attr {
                continue;
            }
            let target = match attr.value {
                Term::Element(e) => e,
                Term::Relation(_) => continue,
            };
            if attr.name == hg.parent_region_attr {
                hg.region_children.entry(target).or_default().push(subject);
                hg.region_parents
                    .entry(subject)
                    .or_default()
                    .push((target, r.stats.confidence));
            } else if attr.name == hg.prototype_attr {
                hg.region_prototypes
                    .entry(subject)
                    .or_default()
                    .push(target);
            }
        }
    }
}

fn find_subject(r: &Relation, subject_attr: ElementId) -> Option<ElementId> {
    for a in &r.attributes {
        if a.name == subject_attr {
            if let Term::Element(e) = a.value {
                return Some(e);
            }
        }
    }
    None
}

// ─────────────────────────────────────────────────────────────────────
// Decoding — see examples/gen_seed_graph.rs for the canonical format
// ─────────────────────────────────────────────────────────────────────

fn read_element(r: &mut Reader<'_>) -> Element {
    let id = ElementId(r.u32());
    let name_count = r.u32() as usize;
    let mut names = Vec::with_capacity(name_count);
    for _ in 0..name_count {
        names.push(r.string());
    }
    let mut embedding = Vec::with_capacity(EMBEDDING_DIM);
    for _ in 0..EMBEDDING_DIM {
        embedding.push(r.f32());
    }
    let stats = read_stats(r);
    let created_at = Tick(r.u64());
    Element {
        id,
        names,
        stats,
        created_at,
        embedding,
    }
}

fn read_relation(r: &mut Reader<'_>) -> Relation {
    let id = RelationId(r.u32());
    let attr_count = r.u32() as usize;
    let mut attributes = Vec::with_capacity(attr_count);
    for _ in 0..attr_count {
        let name = ElementId(r.u32());
        let kind = r.u8();
        let raw = r.u32();
        let value = match kind {
            0 => Term::Element(ElementId(raw)),
            1 => Term::Relation(RelationId(raw)),
            other => panic!("unknown term kind in seed bin: {other}"),
        };
        attributes.push(Attribute { name, value });
    }
    let status = match r.u8() {
        0 => RelationStatus::Asserted,
        1 => RelationStatus::Entailed,
        2 => RelationStatus::Defeasible,
        3 => RelationStatus::Superseded,
        4 => RelationStatus::Retracted,
        other => panic!("unknown relation status in seed bin: {other}"),
    };
    let stats = read_stats(r);
    let priority = r.i8();
    let created_at = Tick(r.u64());
    Relation {
        id,
        attributes,
        status,
        stats,
        priority,
        created_at,
    }
}

fn read_stats(r: &mut Reader<'_>) -> MemoryStats {
    let activation = r.f32();
    let confidence = r.f32();
    let plasticity = r.f32();
    let salience = r.f32();
    let access_count = r.u32();
    let focus_success_count = r.u32();
    let support_count = r.u32();
    let support_diversity = r.u32();
    let prediction_error = r.f32();
    let last_seen = Tick(r.u64());
    let last_accessed_some = r.u8();
    let last_accessed_val = r.u64();
    let last_accessed = if last_accessed_some != 0 {
        Some(Tick(last_accessed_val))
    } else {
        None
    };
    MemoryStats {
        activation,
        confidence,
        plasticity,
        salience,
        access_count,
        focus_success_count,
        support_count,
        support_diversity,
        prediction_error,
        last_seen,
        last_accessed,
    }
}

// ─────────────────────────────────────────────────────────────────────
// Cursor over the embedded byte slice. Every `u32` / `u64` / `f32` is
// little-endian. Panics on read past end — that's a corruption signal,
// not something to recover from at runtime.
// ─────────────────────────────────────────────────────────────────────

struct Reader<'a> {
    bytes: &'a [u8],
    cursor: usize,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, cursor: 0 }
    }

    fn take(&mut self, n: usize) -> &'a [u8] {
        let end = self.cursor + n;
        assert!(
            end <= self.bytes.len(),
            "seed bin read past end at offset {} ({}+{} > {})",
            self.cursor,
            self.cursor,
            n,
            self.bytes.len(),
        );
        let slice = &self.bytes[self.cursor..end];
        self.cursor = end;
        slice
    }

    fn u8(&mut self) -> u8 {
        self.take(1)[0]
    }

    fn i8(&mut self) -> i8 {
        self.take(1)[0] as i8
    }

    fn u32(&mut self) -> u32 {
        let b = self.take(4);
        u32::from_le_bytes([b[0], b[1], b[2], b[3]])
    }

    fn u64(&mut self) -> u64 {
        let b = self.take(8);
        u64::from_le_bytes([b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7]])
    }

    fn f32(&mut self) -> f32 {
        let b = self.take(4);
        f32::from_le_bytes([b[0], b[1], b[2], b[3]])
    }

    fn string(&mut self) -> String {
        let len = self.u32() as usize;
        let bytes = self.take(len);
        String::from_utf8(bytes.to_vec()).expect("seed bin string is not valid UTF-8")
    }

    fn is_done(&self) -> bool {
        self.cursor == self.bytes.len()
    }

    fn remaining(&self) -> usize {
        self.bytes.len() - self.cursor
    }
}

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_expected_counts() {
        let hg = load_seed_graph();
        // 2 anchors + 30 attrs + 15 regions + 8 frames + 2 classes + 15 prototypes
        assert_eq!(hg.elements.len(), 72);
        // 15 region-class + 8 frame-class + 15 region-parent + 15 prototype-attach
        assert_eq!(hg.relations.len(), 53);
    }

    #[test]
    fn anchors_at_fixed_ids() {
        let hg = load_seed_graph();
        assert_eq!(hg.void, ElementId(0));
        assert_eq!(hg.genesis, ElementId(1));
    }

    #[test]
    fn by_name_resolves_anchors() {
        let hg = load_seed_graph();
        assert_eq!(
            hg.by_name.get("genesis").map(|v| v.as_slice()),
            Some(&[hg.genesis][..])
        );
        assert_eq!(
            hg.by_name.get("void").map(|v| v.as_slice()),
            Some(&[hg.void][..])
        );
    }

    #[test]
    fn region_children_of_genesis_has_15_entries() {
        let hg = load_seed_graph();
        let children = hg
            .region_children
            .get(&hg.genesis)
            .expect("GENESIS should have 15 region children");
        assert_eq!(children.len(), 15);
    }

    #[test]
    fn every_seeded_region_has_one_prototype_with_full_embedding() {
        let hg = load_seed_graph();
        let regions = hg
            .region_children
            .get(&hg.genesis)
            .expect("GENESIS region children");
        for region in regions {
            let protos = hg
                .region_prototypes
                .get(region)
                .unwrap_or_else(|| panic!("region {region:?} should have prototypes"));
            assert_eq!(
                protos.len(),
                1,
                "region {region:?} should have exactly one prototype"
            );
            let proto = &hg.elements[protos[0].0 as usize];
            assert_eq!(
                proto.embedding.len(),
                EMBEDDING_DIM,
                "prototype {:?} embedding has wrong length",
                proto.id,
            );
        }
    }

    #[test]
    fn rebuild_indices_is_idempotent() {
        let mut hg = load_seed_graph();
        let before_children = hg.region_children.clone();
        let before_protos = hg.region_prototypes.clone();
        rebuild_indices(&mut hg);
        assert_eq!(hg.region_children, before_children);
        assert_eq!(hg.region_prototypes, before_protos);
    }
}
